package com.kwwsyk.suit.neoforge.data.loot;

import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.neoforged.neoforge.common.loot.IGlobalLootModifier;
import net.neoforged.neoforge.common.loot.LootModifier;

import java.util.ArrayList;
import java.util.List;

public class AddPoolLootModifier extends LootModifier {

    private final List<LootPool> pools = new ArrayList<>();

    public static final MapCodec<AddPoolLootModifier> CODEC = RecordCodecBuilder.mapCodec(
            instance -> instance.group(
                    IGlobalLootModifier.LOOT_CONDITIONS_CODEC.fieldOf("conditions").forGetter(glm -> glm.conditions),
                    Codec.list(LootPool.CODEC).fieldOf("pools").forGetter(AddPoolLootModifier::pools)
            ).apply(instance, AddPoolLootModifier::new)
    );

    public AddPoolLootModifier(LootItemCondition[] conditionsIn, List<LootPool> pools) {
        super(conditionsIn);
        this.pools.addAll(pools);
    }

    public List<LootPool> pools() {
        return pools;
    }

    /**
     * Applies the modifier to the generated loot (all loot conditions have already been checked
     * and have returned true).
     *
     * @param generatedLoot the list of ItemStacks that will be dropped, generated by loot tables
     * @param context       the LootContext, identical to what is passed to loot tables
     * @return modified loot drops
     */
    @Override
    protected ObjectArrayList<ItemStack> doApply(ObjectArrayList<ItemStack> generatedLoot, LootContext context) {
        this.pools.forEach(pool -> pool.addRandomItems(generatedLoot::add, context));
        return generatedLoot;
    }

    /**
     * Returns the registered codec for this modifier
     */
    @Override
    public MapCodec<? extends IGlobalLootModifier> codec() {
        return CODEC;
    }
}
