@ParametersAreNonnullByDefault@MethodsReturnNonnullByDefault
package com.kwwsyk.suit.treasure_marker;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;