@MethodsReturnNonnullByDefault@ParametersAreNonnullByDefault
package com.kwwsyk.suit.suit_yield.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;