#The specific mod info of sub-mod (subproject mod)
mod_name=TreasureMarker
mod_id=treasure_marker

minecraft_version_range=[1.21,1.21.8]
neo_version_range=[21,)
#license=MIT
#credits=Jared(for multiloader-template)
description=Right-click use a treasure map to mark a waypoint of your Map mod.\nJourneyMap available, and you can customize waypoint commands.