@ParametersAreNonnullByDefault@MethodsReturnNonnullByDefault
package com.kwwsyk.suit.suit_yield.datagen.feature;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;